name: Run Tests
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
permissions:
  contents: read
  actions: read
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x, 24.x]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm start &
      - uses: iFaxity/wait-on-action@v1.2.1
        with:
          delay: 1
          timeout: 30000
          resource: tcp:localhost:8082
      - run: npm run test-report
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number
      - uses: actions/upload-artifact@v6
        if: success() || failure()
        with:
          name: test-results-${{ matrix.node-version }}
          path: |
            backend/test-results.json
            pr_number
